### ISSUE TITLE
About Fig.1 Precision-recall curves

### ISSUE THREAD

**Issue by SuleBai** [mc-lan/ProxyCLIP#1]
Thank you for the excellent work!

I found Figure 1 to be very insightful. However, I’m having some difficulty reproducing it. I’ve managed to extract the attention weights from the last layer of CLIP (in the shape `num_heads * seq_len * seq_len`).

Could you please share the code used to plot this figure (perhaps using CLIP's standard attention weights as an example)?

Thank you in advance!

**Comment by mc-lan** [comment]
You could refer to [plot_pr_curves](https://github.com/mhamilton723/STEGO/blob/eb4d6b521740bd4265681b353547f2ffca65d673/src/plot_pr_curves.py).

**Comment by SuleBai** [comment]
Thanks a lot.
