### ISSUE TITLE
Why some baselines in ProxyCLIP and ClearCLIP are different?

### ISSUE THREAD

**Issue by yxchng** [mc-lan/ProxyCLIP#2]
e.g. maskclip and sclip

![Screenshot from 2024-09-27 23-16-29](https://github.com/user-attachments/assets/9ec8dd7d-be8e-4d9c-81bf-16ac58262c20)
![Screenshot from 2024-09-27 23-16-21](https://github.com/user-attachments/assets/679352cf-29a1-4cfb-a65e-bc1b3a05a69c)

**Comment by mc-lan** [comment]
To ensure a fair comparison between methods in ClearCLIP, we report the results of SCLIP based on our implementation. In ProxyCLIP, we present their best results, which may includes some tricks to enhance performance.  The results of MaskCLIP are consistent.
