### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by zhengyuan-xie** [mc-lan/ProxyCLIP#3]
Hi, thanks for your excellent work! I tried to visualize the segmentation results and set --show when running the test command, but there are no visualization results. Did I miss any steps? Looking for your reply.

**Comment by mc-lan** [comment]
Uncomment [_trigger_visualization_hook_](https://github.com/mc-lan/ProxyCLIP/blob/e7b767fbc58ea218a3b8ba34cd92db521cc5f2e1/eval.py#L63). You could adjust the parameters related to the visualization in base_config.

**Comment by zhengyuan-xie** [comment]
It works. Many thanks for your fast reply!
